# Generated by Django 4.0.6 on 2022-07-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suit_price',
            field=models.IntegerField(blank=True),
        ),
    ]
